# remote hosts/groups patterns
- hosts: webservers
  vars:
    http_port: 80
    max_clients: 200
  # user account
  remote_user: yourname
  become: yes
  # task list
  tasks:
    - name: disable selinux
      command: /sbin/setenforce 0
    - name: ensure apache is at the latest version
      yum: pkg=httpd state=latest
      become: yes
      become_user: root
    - name: write the apache config file
      template: src=/srv/httpd.j2 dest=/etc/httpd.conf
  # handlers
  notify: restart apache
    - name: ensure apache is running
      service: name=httpd state=started
  handlers:
    - name: restart apache
      service: name=httpd state=restarted
